[package]
name = "healthchecks-monitor"
version = "1.0.2-alpha.0"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
edition = "2018"
description = "Report results of arbitrary commands to healthchecks.io"
repository = "https://github.com/msfjarvis/healthchecks-rs"
homepage = "https://github.com/msfjarvis/healthchecks-rs"
license = "MIT/Apache-2.0"
keywords = ["healthchecks"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.32"
argh = "0.1.4"
execute = "0.2.8"
healthchecks = { path = "../healthchecks", version = "^1.0.2-alpha.0"}

[badges]
maintenance = { status = "actively-developed" }
